[fix][client] Memory leak during GET_LAST_MESSAGE_ID command processing.
apache/pulsar-client-cpp pull request #301
Opened 2023-07-11 12:18 UTC by fundaev

### Motivation
`ClientConnection::newGetLastMessageId` method uses `ClientConnection::sendRequestWithId` one to send request. It adds a new node into `ClientConnection::pendingRequests_` map. However `ClientConnection::handleGetLastMessageIdResponse` method does not affect this map. As a result the size of mentioned map is increased every time when `Reader::getLastMessageIdAsync` method is called.

### Modifications
`ClientConnection::newGetLastMessageId` method use now `ClientConnection::sendCommand` one to send request.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is already covered by existing tests, such as ConsumerTest.testGetLastMessageId and ConsumerTest.testGetLastMessageIdBlockWhenConnectionDisconnected.

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [] `doc-not-needed` 
(Please explain why)

- [ ] `doc` 
(Your PR contains doc changes)

- [x] `doc-complete`
(Docs have been already added)

2023-07-11 17:15 UTC, Radrik5 commented
This change partially reverts commit https://github.com/apache/pulsar-client-cpp/commit/87351037b72574c1b59379bacc4e7a3d78682521 probably re-injecting timeout issue it fixed.

2023-07-12 16:31 UTC, BewareMyPower requested changes
Just as @Radrik5, it reverts the fix of https://github.com/apache/pulsar/pull/12586.

I think a better solution is to remove the `pendingGetLastMessageIdRequests_` map and remove it from `pendingRequests_` in `handleGetLastMessageIdResponse`.

2023-07-17 06:24 UTC, BewareMyPower commented
Could you address my comment? I will wait for some time. If not, I might open another PR to fix it since I'm going to cut the 3.2.0 release soon (maybe the next week)

2023-07-17 07:10 UTC, fundaev commented
Yes, I'll correct the solution soon. Sorry for the delay.

2023-07-21 17:41 UTC, fundaev commented
Sorry for late response.
Please look at the solution now. I left `pendingGetLastMessageIdRequests_` cache. Otherwise it's necessary to return `Future<Result, ResponseData>` in `ClientConnection::newGetLastMessageId`. But the problem with timeout is fixed now too.

2023-07-24 00:33 UTC, BewareMyPower approved these changes

2023-07-24 02:25 UTC, BewareMyPower requested changes
Please fix the code format

2023-07-24 02:36 UTC, BewareMyPower requested changes

2023-07-24 02:36 UTC, BewareMyPower commented on lib/GetLastMessageIdResponse.h
>  #include <iostream>
```suggestion

#include <iostream>

#include "Future.h"
```

2023-07-24 08:16 UTC, fundaev commented
Should I do anything else after your commit?

2023-07-24 13:31 UTC, BewareMyPower commented
> Should I do anything else after your commit?

No

2023-07-25 03:30 UTC, BewareMyPower approved these changes

2023-07-25 03:31 UTC, merged